### ISSUE TITLE
家事の新規作成

### ISSUE THREAD

**Issue by YutaroObuchi** [YutaroObuchi/kajino#8]
* Kajiテーブルの作成
* 家事を新規作成する機能の実装

**Comment by YutaroObuchi** [comment]
## 前提

*   毎日の家事を数字で可視化するアプリを作りたい
* 「家事」は「ポイント」と紐付いており、各自が自由に作成できる

## 実現したいこと

* 「家事」と「ポイント」が紐付いた状態で、**一括登録**できるようにしたい

ex
[![Image from Gyazo](https://i.gyazo.com/21c16a4fc976882888939f0a5ea8b016.png)](https://gyazo.com/21c16a4fc976882888939f0a5ea8b016)

## 聞きたいこと
下記の実装方法は方向性として誤っていないか？


## 現在考えている実装方法

1. 複数の家事を格納できるコレクションモデルを作成
2. 一画面で複数のデータを登録できるフォームを作成
3. コントローラーでフォームのデータを取得
4. 複数登録用ののsaveメソッドを作成

[参考記事](https://qiita.com/Ryoga_aoym/items/91a3940cfa4de268fca4)


ご回答いただけますと幸いです。
よろしくお願いします！

**Comment by MrFuku** [comment]
@YutaroObuchi 
一括登録するだけであれば、コレクションモデルというものは作らなくてもできます（正直、この記事でそれを採用した必要性が分かりません）

また、rails6から`insert_all`というメソッドが提供されていますので、そちらを使う方法を検討してみてもいいのではないでしょうか？ただし、バリデーションなどは効かないようですので、使用するのであればちゃんと仕様は理解しておいた方が良いと思います（参考記事共有しますが、公式などのより信頼できる記事を読むこともお勧めします）。
https://www.mogulla3.tech/entry/2019/12/02/001739

**Comment by MrFuku** [comment]
> Kajiテーブルの作成

ちなみに日本語のテーブル名はあまり良くないです（念の為）

**Comment by YutaroObuchi** [comment]
コメントありがとうございます！

> insert_allというメソッドが提供されていますので、そちらを使う方法を検討してみてもいいのではないでしょうか？

こちら教えていただきありがとうございます。
記事を参考にしつつ、公式を解読し実装を進めてみたいと思います。


> ちなみに日本語のテーブル名はあまり良くないです（念の為）

こちらも教えて頂きありがとうございます。
houseworkテーブルに変更できればと思います(早いうちに気づけてよかったです)

insert_allの件で不明点がありましたらまたご相談させていただければと思います。
引き続きよろしくお願いします！

**Comment by YutaroObuchi** [comment]
先日教えていただきました、`insert_allメソッド`の件でご質問させていただければと思います。

## 現状

* 新規`housework`を作成するためのフォームを作成
* controllerで保存処理を作成中

## 該当コード

`_form.html.slim`

```
= form_with model: housework, local: true do |f|
  .form-group
    = f.select '[houseworks][][name]', [["洗濯", "洗濯"], ["食器洗い", "食器洗い"], ["掃除機かけ", "掃除機かけ"], ["お風呂掃除", "お風呂掃除"]], include_blank: "選択して下さい", class: 'form-control'
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 1, max: 100

    = f.select '[houseworks][][name]', [["洗濯", "洗濯"], ["食器洗い", "食器洗い"], ["掃除機かけ", "掃除機かけ"], ["お風呂掃除", "お風呂掃除"]], include_blank: "選択して下さい", class: 'form-control'
    = f.number_field '[houseworks][][score]', class: 'form-control', min: 1, max: 100

  = f.submit "作成する", class: 'btn btn-primary'
```

`params内`
```
=> <ActionController::Parameters {"authenticity_token"=>"Tc6nRvYaqllS5F2qE1p/W0PAVir8BsOhgTcPxTTjUmJ/vyW7swddueblaSu/m2JA2qJ8yilng49LnpZs0dBuGA==", "housework"=><ActionController::Parameters {"houseworks"=>[{"name"=>"洗濯", "score"=>"20"}, {"name"=>"掃除機かけ", "score"=>"40"}]} permitted: false>, "commit"=>"作成する", "controller"=>"houseworks", "action"=>"create"} permitted: false>
```

`controller内`

```
  def create
    search_record = GroupUser.find_by(user_id: current_user.id)
    group = Group.find(search_record.group_id)
    #@housework = group.houseworks.build(housework_params)

    array = params[:housework][:houseworks]
    Housework.insert_all(array)

  private

  def housework_params
  	#params.require(:housework).permit(:name, :score)
  	params.require(:housework).permit(houseworks: [%w(name score)])
  end
end
```

## エラー

[![Image from Gyazo](https://i.gyazo.com/d6d200c07fb150b1e5736e937b810a32.png)](https://gyazo.com/d6d200c07fb150b1e5736e937b810a32)


## 思考プロセス

1. `insert_allメソッド`を活用するために、params内を配列化しないといけない
2. 配列化するため、viewを編集
3. controller内で配列化されている
